chores(docs): Fix typos
jeertmans/languagetool-rust pull request #4
Opened 2022-07-25 11:29 UTC by kianmeng

2022-07-25 16:05 UTC, jeertmans requested changes
Hi @kianmeng ! Many thanks for taking the time to review my code :)

There are two comments I have:
- Can you update the correction about « whether » ?
- Can you write a one line change that in the Unreleased/Chore section of the changelog ?

Feel free if you have any other question ;)

2022-07-26 13:49 UTC, kianmeng commented on src/lib/check.rs
> +    /// Tell weather the server uses premium API or not
Seemed you've added the change. :smile:

2022-07-26 17:34 UTC, jeertmans commented on src/lib/check.rs
> +    /// Tell weather the server uses premium API or not
Yes, I wanted to "suggest changes" but I actually committed the fix ^^'

2022-07-26 17:37 UTC, jeertmans approved these changes

2022-07-26 17:54 UTC, merged

2022-07-26 17:55 UTC, jeertmans commented
Merged! Many thanks @kianmeng ;-)

2022-07-27 06:01 UTC, kianmeng commented
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face: