docs(README): Created Installation section
jeertmans/languagetool-rust pull request #77
Opened 2023-04-02 18:52 UTC by Dosx001

# Description
I just updated the README.

I also packaged languagetool-rust for Arch Linux.
https://aur.archlinux.org/packages/languagetool-rust

I added a section on how to install languagetool-rust on Arch Linux using the AUR.

2023-04-02 20:25 UTC, jeertmans commented
Thanks @Dosx001!
Before merging this, I have a small question / comment.

What is the process required to deploy a Arch package?

if this is not complicated, I suggest to automate it. Either you create a GitHub action job that uses some token to automatically publish every time I publish.

You could also use dependabot on another repo you own, watch for updates and be alerted every time I update. Because I cannot promise to ping you every time I upgrade :’-)

2023-04-02 21:09 UTC, Dosx001 commented
@jeertmans it's not that complicated but as of right now I am the maintainer for languagetool-rust on the AUR. I am not sure about this but I believe you would need my SSH Public Key to push changes to the repo. I will have to look into this. I wouldn't mind making this a GitHub action.

2023-04-02 22:14 UTC, Dosx001 commented
Looks like there are ways to send notifications using GitHub Actions.

On Discord
https://www.youtube.com/watch?v=-KDQqWNK3Tw
And Slack
https://www.youtube.com/watch?v=RKfsnp_AN-4

This might be an easier approach. There doesn't seem to be a way to have a forked repo that runs an action when upstream does a release.

2023-04-02 22:17 UTC, Dosx001 commented
WAIIIITTTT!!! LLLOLOLOLOLOLOLO!!! I just could watch the repo and turn on notifications on release.  lol

2023-04-03 13:40 UTC, jeertmans requested changes
Just a few suggested changes :-)

Also, please write something in the CHANGELOG.md, as suggested by the CI :-)

2023-04-03 13:40 UTC, jeertmans commented on README.md
> +```
```suggestion
```

I don't think LTRs needs to tell that. This should be performed only once, and most likely when installing Cargo.

2023-04-03 13:40 UTC, jeertmans commented on README.md
> +If you're on Arch Linux simply.
```suggestion
If you are on Arch Linux, you call also install with the package manager:
```

2023-04-07 08:31 UTC, merged

2023-04-07 08:34 UTC, jeertmans commented
Merged @Dosx001 ! Thanks :-)